# This workflow will deploy onepoint on now.sh platform.

name: Now.sh deploy

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'https://vercel.com/account/tokens'
        required: true
      config_json:
        description: 'onepoint configuration file'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          npm i -g vercel
          cp bin/index_now.js test/nowsh/api/
          echo ${{ github.event.inputs.config_json }} > test/nowsh/api/config.json
          mv test/nowsh test/onepoint
          cd test/onepoint
          vercel --token ${{ github.event.inputs.token }} --confirm
          echo "deploy success"
